version: "3.8"


services:
  redis:
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    ports:
      - "8001:8001"
