version: "3.8"


services:
  redis:
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight
    container_name: redis_insight
    ports:
      - "8001:8001"

  processor:
    build:
      context: .
    image: processor/prediction
    container_name: init_processor
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./app.py:/app/app.py"

